Drop Ruby 2.4 support
This commit drops Ruby 2.4 support and fixes the following build error.

```console
% bundle exec rake
(snip)

Running RuboCop...
Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion`
parameter (in .rubocop.yml). 2.4-compatible analysis was dropped after
version 1.12.
Supported versions: 2.5, 2.6, 2.7, 3.0, 3.1
RuboCop failed!
```